#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/rnglib
  
  blListGen \
    -d ../rnglib \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh -X cover -X coverage \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
