#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/rnglib
  
  rm -rf build/* tmp/* 
  
  pySloc -L py src tests  -X cover -X htmlcov -X dist -v $@
else
  echo "DEV_BASE is not defined"
fi
