[meta]
version = "0.1.0"

[project]
name = "rnglib"
package = "rnglib"
main_lang = "py"
version = "1.3.10"
version_date = "2019-03-19"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2011-2017"
description = "random number generator library"
dev_status = "beta"
license = "mit"
relpath = "py/rnglib"
state = "shared"
url = "https://jddixon.github.io/rnglib"

[py]
packages = [ "rnglib",]
package_dir = [ "src",]
test_dir = "tests"
py_modules = []
scripts = []
ext_modules = []
distshare = []
requirements = []
test_requirements = []
